### ISSUE TITLE
glossing in inflections/paradigms dictionary

### ISSUE THREAD

**Issue by iljackb** [iljackb/Mixtepec_Mixtec#67]
I am entering a lot of content from the literature that has inflected nouns and verbs into my inflections dictionary which is linked to the regular dictionary via a pointer. The dictionary structure is as follows (for a noun):

```
       <entry xml:lang="mix" xml:id="comb-N-paradigm-MIX">
            <form type="lemma">
               <orth xml:lang="mix">kuika</orth>
               <pron notation="ipa" xml:lang="mix"></pron>
            </form>
            <gramGrp>
               <pos>noun</pos>
            </gramGrp>

            <form type="paradigm" subtype="possessive">    
               <gramGrp>
                  <gram norm="possessive">poss</gram>
               </gramGrp>     
               <!-- 1S -->
               <form type="inflected">
                  <orth xml:lang="mix">kuika yu</orth>
                  <pron xml:lang="mix" notation="ipa"></pron> 
                  <gramGrp>
                     <per>1</per>
                     <number norm="singular">sg</number>
                  </gramGrp>
               </form>

               <!-- other forms here -->

            <sense>
               <cit type="translation">
                  <orth xml:lang="en">comb</orth>
               </cit>
               <cit type="translation">
                  <orth xml:lang="es">peine</orth>
               </cit>
            </sense>
         </entry>
```

Since I am entering this content directly into the dictionary and not into a corpus document first, it is possible that there won't be anything in the corpus that comes up in a search for such a possessed or inflected form of a given noun or verb. 

And I don't have time or any desire to deal with any kind of sense pointing mechanism where for each inflected form, I have a sense.. So I am considering putting a `<gloss>` in each form which would solve this issue. So the entry above would be:

```
               <!-- 1S -->
               <form type="inflected">
                  <orth xml:lang="mix">kuika yu</orth>
                  <pron xml:lang="mix" notation="ipa"></pron> 
                  <gramGrp>
                     <per>1</per>
                     <number norm="singular">sg</number>
                  </gramGrp>
                  <gloss xml:lang="en">my comb</gloss>
               </form>
```

I know this is not kosher, but it is actually allowed and in the context of a dictionary specifically for inflected forms, it makes sense..

**Comment by laurentromary** [comment]
I don't have a problem with this and it makes the dictionary even more useful for a variety of users (language learners, comparatists, etc.)

**Comment by iljackb** [comment]
Great I agree it will be more useful for learners etc. thanks!
